[build]
builder = "NIXPACKS"
buildCommand = "npm install && npm run build && npm run db:generate"

[deploy]
startCommand = "npm run start:prod"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
NODE_ENV = "production"